import Elysia from "elysia";
export declare const nutritionModel: Elysia<"", {
    decorator: {};
    store: {};
    derive: {};
    resolve: {};
}, {
    typebox: {
        readonly "nutrition.plans.query": import("@sinclair/typebox").TObject<{
            patientId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            status: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"DRAFT">, import("@sinclair/typebox").TLiteral<"ACTIVE">, import("@sinclair/typebox").TLiteral<"COMPLETED">, import("@sinclair/typebox").TLiteral<"DISCONTINUED">]>>;
            goal: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"MAINTENANCE">, import("@sinclair/typebox").TLiteral<"WEIGHT_LOSS">, import("@sinclair/typebox").TLiteral<"WEIGHT_GAIN">, import("@sinclair/typebox").TLiteral<"GROWTH">, import("@sinclair/typebox").TLiteral<"GESTATION">, import("@sinclair/typebox").TLiteral<"LACTATION">, import("@sinclair/typebox").TLiteral<"RECOVERY">]>>;
            q: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            take: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        }>;
        readonly "nutrition.due.query": import("@sinclair/typebox").TObject<{
            horizonDays: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        }>;
        readonly "nutrition.plans.create": import("@sinclair/typebox").TObject<{
            patientId: import("@sinclair/typebox").TString;
            appointmentId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
            prescriberId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
            goal: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"MAINTENANCE">, import("@sinclair/typebox").TLiteral<"WEIGHT_LOSS">, import("@sinclair/typebox").TLiteral<"WEIGHT_GAIN">, import("@sinclair/typebox").TLiteral<"GROWTH">, import("@sinclair/typebox").TLiteral<"GESTATION">, import("@sinclair/typebox").TLiteral<"LACTATION">, import("@sinclair/typebox").TLiteral<"RECOVERY">]>;
            currentWeightKg: import("@sinclair/typebox").TNumber;
            bodyConditionScore: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TInteger]>>;
            muscleConditionScore: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"NORMAL">, import("@sinclair/typebox").TLiteral<"MILD_LOSS">, import("@sinclair/typebox").TLiteral<"MODERATE_LOSS">, import("@sinclair/typebox").TLiteral<"SEVERE_LOSS">]>]>>;
            idealWeightKg: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TNumber]>>;
            idealWeightSource: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
            lifeStage: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"GROWTH_UNDER_4M">, import("@sinclair/typebox").TLiteral<"GROWTH_OVER_4M">, import("@sinclair/typebox").TLiteral<"ADULT">, import("@sinclair/typebox").TLiteral<"SENIOR">]>;
            activity: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"INACTIVE">, import("@sinclair/typebox").TLiteral<"LOW">, import("@sinclair/typebox").TLiteral<"MODERATE">, import("@sinclair/typebox").TLiteral<"HIGH">, import("@sinclair/typebox").TLiteral<"WORK_LIGHT">, import("@sinclair/typebox").TLiteral<"WORK_MODERATE">, import("@sinclair/typebox").TLiteral<"WORK_HEAVY">]>;
            isNeutered: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
            riskFactors: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
            medicalConditions: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
            feedingMethod: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"MEAL_FED">, import("@sinclair/typebox").TLiteral<"FREE_CHOICE">, import("@sinclair/typebox").TLiteral<"COMBINATION">]>>;
            mealsPerDay: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
            currentDietSummary: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
            treatsSummary: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
            tableFoodSummary: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
            supplementsSummary: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
            medicationFoodSummary: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
            waterSource: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
            environmentNotes: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
            currentTreatCaloriePercent: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TNumber]>>;
            manualDerFactor: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TNumber]>>;
            targetWeeklyRatePercent: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TNumber]>>;
            recheckIntervalDays: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
            items: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TObject<{
                dietFoodId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
                nameSnapshot: import("@sinclair/typebox").TString;
                formSnapshot: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"DRY">, import("@sinclair/typebox").TLiteral<"WET">, import("@sinclair/typebox").TLiteral<"RAW">, import("@sinclair/typebox").TLiteral<"HOME_COOKED">, import("@sinclair/typebox").TLiteral<"TREAT">, import("@sinclair/typebox").TLiteral<"SUPPLEMENT">]>>;
                energyDensityKcalPerKgSnapshot: import("@sinclair/typebox").TNumber;
                energySharePercent: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
                householdUnit: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"GRAM">, import("@sinclair/typebox").TLiteral<"CUP">, import("@sinclair/typebox").TLiteral<"CAN">, import("@sinclair/typebox").TLiteral<"SCOOP">, import("@sinclair/typebox").TLiteral<"PIECE">]>>;
                householdUnitGrams: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TNumber]>>;
                isTreat: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
                notes: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
            }>>>;
            feedingInstructions: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
            clinicalNotes: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
            transitionDays: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TInteger]>>;
        }>;
        readonly "nutrition.plans.update": import("@sinclair/typebox").TObject<{
            patientId: import("@sinclair/typebox").TString;
            appointmentId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
            prescriberId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
            goal: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"MAINTENANCE">, import("@sinclair/typebox").TLiteral<"WEIGHT_LOSS">, import("@sinclair/typebox").TLiteral<"WEIGHT_GAIN">, import("@sinclair/typebox").TLiteral<"GROWTH">, import("@sinclair/typebox").TLiteral<"GESTATION">, import("@sinclair/typebox").TLiteral<"LACTATION">, import("@sinclair/typebox").TLiteral<"RECOVERY">]>;
            currentWeightKg: import("@sinclair/typebox").TNumber;
            bodyConditionScore: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TInteger]>>;
            muscleConditionScore: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"NORMAL">, import("@sinclair/typebox").TLiteral<"MILD_LOSS">, import("@sinclair/typebox").TLiteral<"MODERATE_LOSS">, import("@sinclair/typebox").TLiteral<"SEVERE_LOSS">]>]>>;
            idealWeightKg: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TNumber]>>;
            idealWeightSource: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
            lifeStage: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"GROWTH_UNDER_4M">, import("@sinclair/typebox").TLiteral<"GROWTH_OVER_4M">, import("@sinclair/typebox").TLiteral<"ADULT">, import("@sinclair/typebox").TLiteral<"SENIOR">]>;
            activity: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"INACTIVE">, import("@sinclair/typebox").TLiteral<"LOW">, import("@sinclair/typebox").TLiteral<"MODERATE">, import("@sinclair/typebox").TLiteral<"HIGH">, import("@sinclair/typebox").TLiteral<"WORK_LIGHT">, import("@sinclair/typebox").TLiteral<"WORK_MODERATE">, import("@sinclair/typebox").TLiteral<"WORK_HEAVY">]>;
            isNeutered: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
            riskFactors: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
            medicalConditions: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
            feedingMethod: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"MEAL_FED">, import("@sinclair/typebox").TLiteral<"FREE_CHOICE">, import("@sinclair/typebox").TLiteral<"COMBINATION">]>>;
            mealsPerDay: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
            currentDietSummary: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
            treatsSummary: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
            tableFoodSummary: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
            supplementsSummary: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
            medicationFoodSummary: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
            waterSource: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
            environmentNotes: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
            currentTreatCaloriePercent: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TNumber]>>;
            manualDerFactor: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TNumber]>>;
            targetWeeklyRatePercent: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TNumber]>>;
            recheckIntervalDays: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
            items: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TObject<{
                dietFoodId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
                nameSnapshot: import("@sinclair/typebox").TString;
                formSnapshot: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"DRY">, import("@sinclair/typebox").TLiteral<"WET">, import("@sinclair/typebox").TLiteral<"RAW">, import("@sinclair/typebox").TLiteral<"HOME_COOKED">, import("@sinclair/typebox").TLiteral<"TREAT">, import("@sinclair/typebox").TLiteral<"SUPPLEMENT">]>>;
                energyDensityKcalPerKgSnapshot: import("@sinclair/typebox").TNumber;
                energySharePercent: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
                householdUnit: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"GRAM">, import("@sinclair/typebox").TLiteral<"CUP">, import("@sinclair/typebox").TLiteral<"CAN">, import("@sinclair/typebox").TLiteral<"SCOOP">, import("@sinclair/typebox").TLiteral<"PIECE">]>>;
                householdUnitGrams: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TNumber]>>;
                isTreat: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
                notes: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
            }>>>;
            feedingInstructions: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
            clinicalNotes: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
            transitionDays: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TInteger]>>;
        }>;
        readonly "nutrition.plans.discontinue": import("@sinclair/typebox").TObject<{
            reason: import("@sinclair/typebox").TString;
        }>;
        readonly "nutrition.rechecks.create": import("@sinclair/typebox").TObject<{
            weightKg: import("@sinclair/typebox").TNumber;
            recheckedAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            bodyConditionScore: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TInteger]>>;
            muscleConditionScore: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"NORMAL">, import("@sinclair/typebox").TLiteral<"MILD_LOSS">, import("@sinclair/typebox").TLiteral<"MODERATE_LOSS">, import("@sinclair/typebox").TLiteral<"SEVERE_LOSS">]>]>>;
            ownerAdherence: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TInteger]>>;
            performedById: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
            adjustmentPercent: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TNumber]>>;
            applyAdjustment: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
            adjustmentReason: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
            notes: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
        }>;
        readonly "nutrition.calculate": import("@sinclair/typebox").TObject<{
            patientId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
            species: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"DOG">, import("@sinclair/typebox").TLiteral<"CAT">, import("@sinclair/typebox").TLiteral<"HORSE">, import("@sinclair/typebox").TLiteral<"CATTLE">, import("@sinclair/typebox").TLiteral<"SHEEP">, import("@sinclair/typebox").TLiteral<"GOAT">, import("@sinclair/typebox").TLiteral<"CAMEL">, import("@sinclair/typebox").TLiteral<"POULTRY">, import("@sinclair/typebox").TLiteral<"RABBIT">, import("@sinclair/typebox").TLiteral<"SWINE">, import("@sinclair/typebox").TLiteral<"FISH">, import("@sinclair/typebox").TLiteral<"BEE">]>]>>;
            goal: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"MAINTENANCE">, import("@sinclair/typebox").TLiteral<"WEIGHT_LOSS">, import("@sinclair/typebox").TLiteral<"WEIGHT_GAIN">, import("@sinclair/typebox").TLiteral<"GROWTH">, import("@sinclair/typebox").TLiteral<"GESTATION">, import("@sinclair/typebox").TLiteral<"LACTATION">, import("@sinclair/typebox").TLiteral<"RECOVERY">]>;
            lifeStage: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"GROWTH_UNDER_4M">, import("@sinclair/typebox").TLiteral<"GROWTH_OVER_4M">, import("@sinclair/typebox").TLiteral<"ADULT">, import("@sinclair/typebox").TLiteral<"SENIOR">]>;
            activity: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"INACTIVE">, import("@sinclair/typebox").TLiteral<"LOW">, import("@sinclair/typebox").TLiteral<"MODERATE">, import("@sinclair/typebox").TLiteral<"HIGH">, import("@sinclair/typebox").TLiteral<"WORK_LIGHT">, import("@sinclair/typebox").TLiteral<"WORK_MODERATE">, import("@sinclair/typebox").TLiteral<"WORK_HEAVY">]>;
            isNeutered: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
            currentWeightKg: import("@sinclair/typebox").TNumber;
            idealWeightKg: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TNumber]>>;
            bodyConditionScore: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TInteger]>>;
            manualDerFactor: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TNumber]>>;
            targetWeeklyRatePercent: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TNumber]>>;
            mealsPerDay: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
            foods: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TObject<{
                dietFoodId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
                nameSnapshot: import("@sinclair/typebox").TString;
                formSnapshot: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"DRY">, import("@sinclair/typebox").TLiteral<"WET">, import("@sinclair/typebox").TLiteral<"RAW">, import("@sinclair/typebox").TLiteral<"HOME_COOKED">, import("@sinclair/typebox").TLiteral<"TREAT">, import("@sinclair/typebox").TLiteral<"SUPPLEMENT">]>>;
                energyDensityKcalPerKgSnapshot: import("@sinclair/typebox").TNumber;
                energySharePercent: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
                householdUnit: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"GRAM">, import("@sinclair/typebox").TLiteral<"CUP">, import("@sinclair/typebox").TLiteral<"CAN">, import("@sinclair/typebox").TLiteral<"SCOOP">, import("@sinclair/typebox").TLiteral<"PIECE">]>>;
                householdUnitGrams: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TNumber]>>;
                isTreat: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
                notes: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
            }>>>;
        }>;
        readonly "nutrition.foods.query": import("@sinclair/typebox").TObject<{
            q: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            patientId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            species: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"DOG">, import("@sinclair/typebox").TLiteral<"CAT">, import("@sinclair/typebox").TLiteral<"HORSE">, import("@sinclair/typebox").TLiteral<"CATTLE">, import("@sinclair/typebox").TLiteral<"SHEEP">, import("@sinclair/typebox").TLiteral<"GOAT">, import("@sinclair/typebox").TLiteral<"CAMEL">, import("@sinclair/typebox").TLiteral<"POULTRY">, import("@sinclair/typebox").TLiteral<"RABBIT">, import("@sinclair/typebox").TLiteral<"SWINE">, import("@sinclair/typebox").TLiteral<"FISH">, import("@sinclair/typebox").TLiteral<"BEE">]>>;
            kind: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"MAINTENANCE">, import("@sinclair/typebox").TLiteral<"THERAPEUTIC">, import("@sinclair/typebox").TLiteral<"TREAT">, import("@sinclair/typebox").TLiteral<"SUPPLEMENT">]>>;
            form: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"DRY">, import("@sinclair/typebox").TLiteral<"WET">, import("@sinclair/typebox").TLiteral<"RAW">, import("@sinclair/typebox").TLiteral<"HOME_COOKED">, import("@sinclair/typebox").TLiteral<"TREAT">, import("@sinclair/typebox").TLiteral<"SUPPLEMENT">]>>;
            activeOnly: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        }>;
        readonly "nutrition.foods.create": import("@sinclair/typebox").TObject<{
            name: import("@sinclair/typebox").TString;
            nameEn: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
            brand: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
            form: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"DRY">, import("@sinclair/typebox").TLiteral<"WET">, import("@sinclair/typebox").TLiteral<"RAW">, import("@sinclair/typebox").TLiteral<"HOME_COOKED">, import("@sinclair/typebox").TLiteral<"TREAT">, import("@sinclair/typebox").TLiteral<"SUPPLEMENT">]>>;
            kind: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"MAINTENANCE">, import("@sinclair/typebox").TLiteral<"THERAPEUTIC">, import("@sinclair/typebox").TLiteral<"TREAT">, import("@sinclair/typebox").TLiteral<"SUPPLEMENT">]>>;
            metabolizableEnergyKcalPerKg: import("@sinclair/typebox").TNumber;
            householdUnit: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"GRAM">, import("@sinclair/typebox").TLiteral<"CUP">, import("@sinclair/typebox").TLiteral<"CAN">, import("@sinclair/typebox").TLiteral<"SCOOP">, import("@sinclair/typebox").TLiteral<"PIECE">]>>;
            householdUnitGrams: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TNumber]>>;
            proteinPercentDm: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TNumber]>>;
            fatPercentDm: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TNumber]>>;
            fiberPercentDm: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TNumber]>>;
            moisturePercent: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TNumber]>>;
            sodiumPercentDm: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TNumber]>>;
            phosphorusPercentDm: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TNumber]>>;
            species: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"DOG">, import("@sinclair/typebox").TLiteral<"CAT">, import("@sinclair/typebox").TLiteral<"HORSE">, import("@sinclair/typebox").TLiteral<"CATTLE">, import("@sinclair/typebox").TLiteral<"SHEEP">, import("@sinclair/typebox").TLiteral<"GOAT">, import("@sinclair/typebox").TLiteral<"CAMEL">, import("@sinclair/typebox").TLiteral<"POULTRY">, import("@sinclair/typebox").TLiteral<"RABBIT">, import("@sinclair/typebox").TLiteral<"SWINE">, import("@sinclair/typebox").TLiteral<"FISH">, import("@sinclair/typebox").TLiteral<"BEE">]>>>;
            indications: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
            lifeStages: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"GROWTH_UNDER_4M">, import("@sinclair/typebox").TLiteral<"GROWTH_OVER_4M">, import("@sinclair/typebox").TLiteral<"ADULT">, import("@sinclair/typebox").TLiteral<"SENIOR">]>>>;
            inventoryItemId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
            notes: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
            active: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        }>;
        readonly "nutrition.draftInstructions": import("@sinclair/typebox").TObject<{
            hint: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
        }>;
        readonly "nutrition.draftField": import("@sinclair/typebox").TObject<{
            kind: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"instructions">, import("@sinclair/typebox").TLiteral<"clinicalNotes">]>;
            patientId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
            goal: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"MAINTENANCE">, import("@sinclair/typebox").TLiteral<"WEIGHT_LOSS">, import("@sinclair/typebox").TLiteral<"WEIGHT_GAIN">, import("@sinclair/typebox").TLiteral<"GROWTH">, import("@sinclair/typebox").TLiteral<"GESTATION">, import("@sinclair/typebox").TLiteral<"LACTATION">, import("@sinclair/typebox").TLiteral<"RECOVERY">]>;
            lifeStage: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"GROWTH_UNDER_4M">, import("@sinclair/typebox").TLiteral<"GROWTH_OVER_4M">, import("@sinclair/typebox").TLiteral<"ADULT">, import("@sinclair/typebox").TLiteral<"SENIOR">]>;
            activity: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"INACTIVE">, import("@sinclair/typebox").TLiteral<"LOW">, import("@sinclair/typebox").TLiteral<"MODERATE">, import("@sinclair/typebox").TLiteral<"HIGH">, import("@sinclair/typebox").TLiteral<"WORK_LIGHT">, import("@sinclair/typebox").TLiteral<"WORK_MODERATE">, import("@sinclair/typebox").TLiteral<"WORK_HEAVY">]>;
            isNeutered: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
            currentWeightKg: import("@sinclair/typebox").TNumber;
            idealWeightKg: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TNumber]>>;
            bodyConditionScore: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TInteger]>>;
            muscleConditionScore: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"NORMAL">, import("@sinclair/typebox").TLiteral<"MILD_LOSS">, import("@sinclair/typebox").TLiteral<"MODERATE_LOSS">, import("@sinclair/typebox").TLiteral<"SEVERE_LOSS">]>]>>;
            manualDerFactor: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TNumber]>>;
            targetWeeklyRatePercent: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TNumber]>>;
            mealsPerDay: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
            feedingMethod: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"MEAL_FED">, import("@sinclair/typebox").TLiteral<"FREE_CHOICE">, import("@sinclair/typebox").TLiteral<"COMBINATION">]>>;
            recheckIntervalDays: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
            transitionDays: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TInteger]>>;
            riskFactors: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
            medicalConditions: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
            currentDietSummary: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
            treatsSummary: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
            items: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TObject<{
                dietFoodId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
                nameSnapshot: import("@sinclair/typebox").TString;
                formSnapshot: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"DRY">, import("@sinclair/typebox").TLiteral<"WET">, import("@sinclair/typebox").TLiteral<"RAW">, import("@sinclair/typebox").TLiteral<"HOME_COOKED">, import("@sinclair/typebox").TLiteral<"TREAT">, import("@sinclair/typebox").TLiteral<"SUPPLEMENT">]>>;
                energyDensityKcalPerKgSnapshot: import("@sinclair/typebox").TNumber;
                energySharePercent: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
                householdUnit: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"GRAM">, import("@sinclair/typebox").TLiteral<"CUP">, import("@sinclair/typebox").TLiteral<"CAN">, import("@sinclair/typebox").TLiteral<"SCOOP">, import("@sinclair/typebox").TLiteral<"PIECE">]>>;
                householdUnitGrams: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TNumber]>>;
                isTreat: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
                notes: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
            }>>>;
            hint: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNull, import("@sinclair/typebox").TString]>>;
        }>;
    };
    error: {};
}, {
    schema: {};
    standaloneSchema: {};
    macro: {};
    macroFn: {};
    parser: {};
    response: {};
}, {}, {
    derive: {};
    resolve: {};
    schema: {};
    standaloneSchema: {};
    response: {};
}, {
    derive: {};
    resolve: {};
    schema: {};
    standaloneSchema: {};
    response: {};
}>;
