import { type ListJournalEntryFilter } from "@/server/accounting/journal-entry/journal-entry.type";
export declare const journalEntryDao: {
    list(clinicId: string, filter?: ListJournalEntryFilter): import("../../../../generated/prisma/internal/prismaNamespace").PrismaPromise<{
        id: string;
        clinicId: string;
        createdById: string | null;
        createdAt: Date;
        updatedAt: Date;
        docstatus: import("@/server/accounting/journal-entry/journal-entry.type").DocStatus;
        amendedFromId: string | null;
        submittedAt: Date | null;
        submittedById: string | null;
        cancelledAt: Date | null;
        cancelledById: string | null;
        postingDate: Date;
        rows: {
            account: {
                accountName: string;
                accountNumber: string | null;
                accountType: import("../../../../generated/prisma/enums").AccountType | null;
            };
            id: string;
            idx: number;
            costCenterId: string | null;
            accountId: string;
            debit: import("@prisma/client-runtime-utils").Decimal;
            credit: import("@prisma/client-runtime-utils").Decimal;
            debitInAccountCurrency: import("@prisma/client-runtime-utils").Decimal;
            creditInAccountCurrency: import("@prisma/client-runtime-utils").Decimal;
            partyType: string | null;
            partyId: string | null;
            dim1: string | null;
            dim2: string | null;
            dim3: string | null;
            dim4: string | null;
            userRemark: string | null;
            exchangeRate: import("@prisma/client-runtime-utils").Decimal;
            referenceType: string | null;
            referenceId: string | null;
        }[];
        voucherType: string;
        documentNo: string | null;
        chequeNo: string | null;
        chequeDate: Date | null;
        remark: string | null;
        multiCurrency: boolean;
        isSystemGenerated: boolean;
        totalDebit: import("@prisma/client-runtime-utils").Decimal;
        totalCredit: import("@prisma/client-runtime-utils").Decimal;
    }[]>;
    findById(clinicId: string, id: string): import("../../../../generated/prisma/models").Prisma__JournalEntryClient<{
        id: string;
        clinicId: string;
        createdById: string | null;
        createdAt: Date;
        updatedAt: Date;
        docstatus: import("@/server/accounting/journal-entry/journal-entry.type").DocStatus;
        amendedFromId: string | null;
        submittedAt: Date | null;
        submittedById: string | null;
        cancelledAt: Date | null;
        cancelledById: string | null;
        postingDate: Date;
        rows: {
            account: {
                accountName: string;
                accountNumber: string | null;
                accountType: import("../../../../generated/prisma/enums").AccountType | null;
            };
            id: string;
            idx: number;
            costCenterId: string | null;
            accountId: string;
            debit: import("@prisma/client-runtime-utils").Decimal;
            credit: import("@prisma/client-runtime-utils").Decimal;
            debitInAccountCurrency: import("@prisma/client-runtime-utils").Decimal;
            creditInAccountCurrency: import("@prisma/client-runtime-utils").Decimal;
            partyType: string | null;
            partyId: string | null;
            dim1: string | null;
            dim2: string | null;
            dim3: string | null;
            dim4: string | null;
            userRemark: string | null;
            exchangeRate: import("@prisma/client-runtime-utils").Decimal;
            referenceType: string | null;
            referenceId: string | null;
        }[];
        voucherType: string;
        documentNo: string | null;
        chequeNo: string | null;
        chequeDate: Date | null;
        remark: string | null;
        multiCurrency: boolean;
        isSystemGenerated: boolean;
        totalDebit: import("@prisma/client-runtime-utils").Decimal;
        totalCredit: import("@prisma/client-runtime-utils").Decimal;
    } | null, null, import("@prisma/client/runtime/client").DefaultArgs, {
        omit: import("../../../../generated/prisma/internal/prismaNamespace").GlobalOmitConfig | undefined;
    }>;
    listTemplates(clinicId: string): import("../../../../generated/prisma/internal/prismaNamespace").PrismaPromise<{
        id: string;
        clinicId: string;
        createdAt: Date;
        updatedAt: Date;
        accountIds: string[];
        voucherType: string;
        templateTitle: string;
    }[]>;
};
