import { type CreateExchangeRateRevaluationInput, DocStatus, type ExchangeRateRevaluationResponse } from "@/server/accounting/exchange-rate-revaluation/exchange-rate-revaluation.type";
import { type VoucherActor } from "@/server/accounting/voucher/voucher.service";
export type ErrScanRow = {
    accountId: string;
    accountName: string;
    accountCurrencyCode: string;
    partyType: string | null;
    partyId: string | null;
    balanceInAccountCurrency: string;
    bookedBase: string;
    /** §4.7 stored-rate suggestion at the scan date (editable on the row) */
    currentExchangeRate: string;
    newBase: string;
    gainLoss: string;
    isZeroForeignSweep: boolean;
};
/** FR-9.3 — the account scan (incl. party sub-balances), pure read. */
export declare function scanRevaluationRows(clinicId: string, postingDate: Date): Promise<ErrScanRow[]>;
export declare function createExchangeRateRevaluation(input: CreateExchangeRateRevaluationInput): Promise<ExchangeRateRevaluationResponse>;
export declare function deleteExchangeRateRevaluation(clinicId: string, id: string): Promise<void>;
export declare function listExchangeRateRevaluations(clinicId: string): Promise<{
    id: string;
    clinicId: string;
    createdById: string | null;
    createdAt: Date;
    updatedAt: Date;
    docstatus: DocStatus;
    amendedFromId: string | null;
    submittedAt: Date | null;
    submittedById: string | null;
    cancelledAt: Date | null;
    cancelledById: string | null;
    postingDate: Date;
    rows: {
        account: {
            accountName: string;
            accountNumber: string | null;
        };
        id: string;
        accountCurrencyCode: string;
        idx: number;
        accountId: string;
        partyType: string | null;
        partyId: string | null;
        balanceInAccountCurrency: import("@prisma/client-runtime-utils").Decimal;
        bookedBase: import("@prisma/client-runtime-utils").Decimal;
        currentExchangeRate: import("@prisma/client-runtime-utils").Decimal;
        newBase: import("@prisma/client-runtime-utils").Decimal;
        gainLoss: import("@prisma/client-runtime-utils").Decimal;
        isZeroForeignSweep: boolean;
    }[];
    documentNo: string | null;
    journalEntryId: string | null;
    roundingLossAllowance: import("@prisma/client-runtime-utils").Decimal;
    totalGainLoss: import("@prisma/client-runtime-utils").Decimal;
}[]>;
export declare function getExchangeRateRevaluation(clinicId: string, id: string): Promise<{
    id: string;
    clinicId: string;
    createdById: string | null;
    createdAt: Date;
    updatedAt: Date;
    docstatus: DocStatus;
    amendedFromId: string | null;
    submittedAt: Date | null;
    submittedById: string | null;
    cancelledAt: Date | null;
    cancelledById: string | null;
    postingDate: Date;
    rows: {
        account: {
            accountName: string;
            accountNumber: string | null;
        };
        id: string;
        accountCurrencyCode: string;
        idx: number;
        accountId: string;
        partyType: string | null;
        partyId: string | null;
        balanceInAccountCurrency: import("@prisma/client-runtime-utils").Decimal;
        bookedBase: import("@prisma/client-runtime-utils").Decimal;
        currentExchangeRate: import("@prisma/client-runtime-utils").Decimal;
        newBase: import("@prisma/client-runtime-utils").Decimal;
        gainLoss: import("@prisma/client-runtime-utils").Decimal;
        isZeroForeignSweep: boolean;
    }[];
    documentNo: string | null;
    journalEntryId: string | null;
    roundingLossAllowance: import("@prisma/client-runtime-utils").Decimal;
    totalGainLoss: import("@prisma/client-runtime-utils").Decimal;
}>;
export declare const submitExchangeRateRevaluation: (id: string, actor: VoucherActor) => Promise<{
    id: string;
    clinicId: string;
    createdById: string | null;
    createdAt: Date;
    updatedAt: Date;
    docstatus: DocStatus;
    amendedFromId: string | null;
    submittedAt: Date | null;
    submittedById: string | null;
    cancelledAt: Date | null;
    cancelledById: string | null;
    postingDate: Date;
    rows: {
        account: {
            accountName: string;
            accountNumber: string | null;
        };
        id: string;
        accountCurrencyCode: string;
        idx: number;
        accountId: string;
        partyType: string | null;
        partyId: string | null;
        balanceInAccountCurrency: import("@prisma/client-runtime-utils").Decimal;
        bookedBase: import("@prisma/client-runtime-utils").Decimal;
        currentExchangeRate: import("@prisma/client-runtime-utils").Decimal;
        newBase: import("@prisma/client-runtime-utils").Decimal;
        gainLoss: import("@prisma/client-runtime-utils").Decimal;
        isZeroForeignSweep: boolean;
    }[];
    documentNo: string | null;
    journalEntryId: string | null;
    roundingLossAllowance: import("@prisma/client-runtime-utils").Decimal;
    totalGainLoss: import("@prisma/client-runtime-utils").Decimal;
}>;
export declare const cancelExchangeRateRevaluation: (id: string, actor: VoucherActor) => Promise<{
    id: string;
    clinicId: string;
    createdById: string | null;
    createdAt: Date;
    updatedAt: Date;
    docstatus: DocStatus;
    amendedFromId: string | null;
    submittedAt: Date | null;
    submittedById: string | null;
    cancelledAt: Date | null;
    cancelledById: string | null;
    postingDate: Date;
    rows: {
        account: {
            accountName: string;
            accountNumber: string | null;
        };
        id: string;
        accountCurrencyCode: string;
        idx: number;
        accountId: string;
        partyType: string | null;
        partyId: string | null;
        balanceInAccountCurrency: import("@prisma/client-runtime-utils").Decimal;
        bookedBase: import("@prisma/client-runtime-utils").Decimal;
        currentExchangeRate: import("@prisma/client-runtime-utils").Decimal;
        newBase: import("@prisma/client-runtime-utils").Decimal;
        gainLoss: import("@prisma/client-runtime-utils").Decimal;
        isZeroForeignSweep: boolean;
    }[];
    documentNo: string | null;
    journalEntryId: string | null;
    roundingLossAllowance: import("@prisma/client-runtime-utils").Decimal;
    totalGainLoss: import("@prisma/client-runtime-utils").Decimal;
}>;
export declare const amendExchangeRateRevaluation: (id: string, actor: VoucherActor) => Promise<{
    id: string;
    clinicId: string;
    createdById: string | null;
    createdAt: Date;
    updatedAt: Date;
    docstatus: DocStatus;
    amendedFromId: string | null;
    submittedAt: Date | null;
    submittedById: string | null;
    cancelledAt: Date | null;
    cancelledById: string | null;
    postingDate: Date;
    rows: {
        account: {
            accountName: string;
            accountNumber: string | null;
        };
        id: string;
        accountCurrencyCode: string;
        idx: number;
        accountId: string;
        partyType: string | null;
        partyId: string | null;
        balanceInAccountCurrency: import("@prisma/client-runtime-utils").Decimal;
        bookedBase: import("@prisma/client-runtime-utils").Decimal;
        currentExchangeRate: import("@prisma/client-runtime-utils").Decimal;
        newBase: import("@prisma/client-runtime-utils").Decimal;
        gainLoss: import("@prisma/client-runtime-utils").Decimal;
        isZeroForeignSweep: boolean;
    }[];
    documentNo: string | null;
    journalEntryId: string | null;
    roundingLossAllowance: import("@prisma/client-runtime-utils").Decimal;
    totalGainLoss: import("@prisma/client-runtime-utils").Decimal;
}>;
