import { z } from "zod";
import type { Prisma } from "@/generated/prisma/client";
export declare const ledgerAccountSelect: {
    readonly id: true;
    readonly clinicId: true;
    readonly accountName: true;
    readonly accountNumber: true;
    readonly parentAccountId: true;
    readonly isGroup: true;
    readonly rootType: true;
    readonly reportType: true;
    readonly accountType: true;
    readonly accountCurrencyCode: true;
    readonly taxRate: true;
    readonly balanceMustBe: true;
    readonly freezeAccount: true;
    readonly disabled: true;
    readonly lft: true;
    readonly rgt: true;
    readonly createdAt: true;
    readonly updatedAt: true;
};
export type LedgerAccountResponse = Prisma.LedgerAccountGetPayload<{
    select: typeof ledgerAccountSelect;
}>;
export declare const createAccountSchema: z.ZodObject<{
    accountName: z.ZodString;
    accountNumber: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    parentAccountId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    isGroup: z.ZodDefault<z.ZodOptional<z.ZodBoolean>>;
    rootType: z.ZodEnum<{
        readonly ASSET: "ASSET";
        readonly LIABILITY: "LIABILITY";
        readonly INCOME: "INCOME";
        readonly EXPENSE: "EXPENSE";
        readonly EQUITY: "EQUITY";
    }>;
    accountType: z.ZodOptional<z.ZodNullable<z.ZodEnum<{
        readonly BANK: "BANK";
        readonly CASH: "CASH";
        readonly RECEIVABLE: "RECEIVABLE";
        readonly PAYABLE: "PAYABLE";
        readonly TAX: "TAX";
        readonly STOCK: "STOCK";
        readonly FIXED_ASSET: "FIXED_ASSET";
        readonly ACCUMULATED_DEPRECIATION: "ACCUMULATED_DEPRECIATION";
        readonly DEPRECIATION: "DEPRECIATION";
        readonly EXPENSE_ACCOUNT: "EXPENSE_ACCOUNT";
        readonly INCOME_ACCOUNT: "INCOME_ACCOUNT";
        readonly CHARGEABLE: "CHARGEABLE";
        readonly ROUND_OFF: "ROUND_OFF";
        readonly ROUND_OFF_FOR_OPENING: "ROUND_OFF_FOR_OPENING";
        readonly TEMPORARY: "TEMPORARY";
        readonly EQUITY: "EQUITY";
        readonly DIRECT_INCOME: "DIRECT_INCOME";
        readonly INDIRECT_INCOME: "INDIRECT_INCOME";
        readonly DIRECT_EXPENSE: "DIRECT_EXPENSE";
        readonly INDIRECT_EXPENSE: "INDIRECT_EXPENSE";
        readonly COST_OF_GOODS_SOLD: "COST_OF_GOODS_SOLD";
        readonly CURRENT_ASSET: "CURRENT_ASSET";
        readonly CURRENT_LIABILITY: "CURRENT_LIABILITY";
        readonly CAPITAL_WORK_IN_PROGRESS: "CAPITAL_WORK_IN_PROGRESS";
        readonly ASSET_RECEIVED_BUT_NOT_BILLED: "ASSET_RECEIVED_BUT_NOT_BILLED";
        readonly STOCK_RECEIVED_BUT_NOT_BILLED: "STOCK_RECEIVED_BUT_NOT_BILLED";
        readonly SERVICE_RECEIVED_BUT_NOT_BILLED: "SERVICE_RECEIVED_BUT_NOT_BILLED";
        readonly STOCK_ADJUSTMENT: "STOCK_ADJUSTMENT";
    }>>>;
    accountCurrencyCode: z.ZodOptional<z.ZodString>;
    taxRate: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    balanceMustBe: z.ZodDefault<z.ZodOptional<z.ZodEnum<{
        readonly NONE: "NONE";
        readonly DEBIT: "DEBIT";
        readonly CREDIT: "CREDIT";
    }>>>;
    freezeAccount: z.ZodDefault<z.ZodOptional<z.ZodBoolean>>;
    disabled: z.ZodDefault<z.ZodOptional<z.ZodBoolean>>;
}, z.core.$strip>;
export type CreateAccountFormInput = z.input<typeof createAccountSchema>;
export type CreateAccountFormValues = z.output<typeof createAccountSchema>;
export declare const updateAccountSchema: z.ZodObject<{
    accountName: z.ZodOptional<z.ZodString>;
    accountNumber: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    accountType: z.ZodOptional<z.ZodNullable<z.ZodEnum<{
        readonly BANK: "BANK";
        readonly CASH: "CASH";
        readonly RECEIVABLE: "RECEIVABLE";
        readonly PAYABLE: "PAYABLE";
        readonly TAX: "TAX";
        readonly STOCK: "STOCK";
        readonly FIXED_ASSET: "FIXED_ASSET";
        readonly ACCUMULATED_DEPRECIATION: "ACCUMULATED_DEPRECIATION";
        readonly DEPRECIATION: "DEPRECIATION";
        readonly EXPENSE_ACCOUNT: "EXPENSE_ACCOUNT";
        readonly INCOME_ACCOUNT: "INCOME_ACCOUNT";
        readonly CHARGEABLE: "CHARGEABLE";
        readonly ROUND_OFF: "ROUND_OFF";
        readonly ROUND_OFF_FOR_OPENING: "ROUND_OFF_FOR_OPENING";
        readonly TEMPORARY: "TEMPORARY";
        readonly EQUITY: "EQUITY";
        readonly DIRECT_INCOME: "DIRECT_INCOME";
        readonly INDIRECT_INCOME: "INDIRECT_INCOME";
        readonly DIRECT_EXPENSE: "DIRECT_EXPENSE";
        readonly INDIRECT_EXPENSE: "INDIRECT_EXPENSE";
        readonly COST_OF_GOODS_SOLD: "COST_OF_GOODS_SOLD";
        readonly CURRENT_ASSET: "CURRENT_ASSET";
        readonly CURRENT_LIABILITY: "CURRENT_LIABILITY";
        readonly CAPITAL_WORK_IN_PROGRESS: "CAPITAL_WORK_IN_PROGRESS";
        readonly ASSET_RECEIVED_BUT_NOT_BILLED: "ASSET_RECEIVED_BUT_NOT_BILLED";
        readonly STOCK_RECEIVED_BUT_NOT_BILLED: "STOCK_RECEIVED_BUT_NOT_BILLED";
        readonly SERVICE_RECEIVED_BUT_NOT_BILLED: "SERVICE_RECEIVED_BUT_NOT_BILLED";
        readonly STOCK_ADJUSTMENT: "STOCK_ADJUSTMENT";
    }>>>;
    accountCurrencyCode: z.ZodOptional<z.ZodString>;
    taxRate: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    balanceMustBe: z.ZodOptional<z.ZodEnum<{
        readonly NONE: "NONE";
        readonly DEBIT: "DEBIT";
        readonly CREDIT: "CREDIT";
    }>>;
    freezeAccount: z.ZodOptional<z.ZodBoolean>;
    disabled: z.ZodOptional<z.ZodBoolean>;
    isGroup: z.ZodOptional<z.ZodBoolean>;
}, z.core.$strip>;
export type UpdateAccountFormInput = z.infer<typeof updateAccountSchema>;
export declare const moveAccountSchema: z.ZodObject<{
    parentAccountId: z.ZodNullable<z.ZodString>;
}, z.core.$strip>;
export type MoveAccountFormInput = z.infer<typeof moveAccountSchema>;
type AccountCreateFields = Prisma.LedgerAccountUncheckedCreateInput;
export type CreateLedgerAccountInput = Pick<AccountCreateFields, "clinicId" | "accountName" | "rootType"> & Partial<Pick<AccountCreateFields, "accountNumber" | "parentAccountId" | "isGroup" | "accountType" | "accountCurrencyCode" | "taxRate" | "balanceMustBe" | "freezeAccount" | "disabled" | "createdById">>;
export type UpdateLedgerAccountInput = Partial<Pick<AccountCreateFields, "accountName" | "accountNumber" | "accountType" | "accountCurrencyCode" | "taxRate" | "balanceMustBe" | "freezeAccount" | "disabled" | "isGroup">>;
export {};
