import { type CreateLedgerAccountInput, type UpdateLedgerAccountInput } from "@/server/accounting/account/account.type";
export declare function createLedgerAccount(input: CreateLedgerAccountInput): Promise<{
    id: string;
    clinicId: string;
    disabled: boolean;
    createdAt: Date;
    updatedAt: Date;
    accountName: string;
    accountNumber: string | null;
    parentAccountId: string | null;
    isGroup: boolean;
    rootType: import("@/generated/prisma/client").AccountRootType;
    reportType: import("@/generated/prisma/client").AccountReportType;
    accountType: import("@/generated/prisma/client").AccountType | null;
    accountCurrencyCode: string;
    taxRate: import("@prisma/client-runtime-utils").Decimal | null;
    balanceMustBe: import("@/generated/prisma/client").BalanceMustBe;
    freezeAccount: boolean;
    lft: number;
    rgt: number;
}>;
export declare function updateLedgerAccount(clinicId: string, id: string, data: UpdateLedgerAccountInput): Promise<{
    id: string;
    clinicId: string;
    disabled: boolean;
    createdAt: Date;
    updatedAt: Date;
    accountName: string;
    accountNumber: string | null;
    parentAccountId: string | null;
    isGroup: boolean;
    rootType: import("@/generated/prisma/client").AccountRootType;
    reportType: import("@/generated/prisma/client").AccountReportType;
    accountType: import("@/generated/prisma/client").AccountType | null;
    accountCurrencyCode: string;
    taxRate: import("@prisma/client-runtime-utils").Decimal | null;
    balanceMustBe: import("@/generated/prisma/client").BalanceMustBe;
    freezeAccount: boolean;
    lft: number;
    rgt: number;
}>;
export declare function moveLedgerAccount(clinicId: string, id: string, newParentId: string | null): Promise<{
    id: string;
    clinicId: string;
    disabled: boolean;
    createdAt: Date;
    updatedAt: Date;
    accountName: string;
    accountNumber: string | null;
    parentAccountId: string | null;
    isGroup: boolean;
    rootType: import("@/generated/prisma/client").AccountRootType;
    reportType: import("@/generated/prisma/client").AccountReportType;
    accountType: import("@/generated/prisma/client").AccountType | null;
    accountCurrencyCode: string;
    taxRate: import("@prisma/client-runtime-utils").Decimal | null;
    balanceMustBe: import("@/generated/prisma/client").BalanceMustBe;
    freezeAccount: boolean;
    lft: number;
    rgt: number;
}>;
export declare function deleteLedgerAccount(clinicId: string, id: string): Promise<void>;
