import { type UpdateSchedulingSettingsInput } from "@/server/scheduling/scheduling.type";
export declare const schedulingDao: {
    get(clinicId: string): Promise<{
        id: string;
        clinicId: string;
        morningStartMinute: number;
        morningEndMinute: number;
        eveningStartMinute: number;
        eveningEndMinute: number;
        onlineBookingEnabled: boolean;
        schedulingEnabled: boolean;
        workDays: import("../staff-scheduling/staff-scheduling.type").Weekday[];
        shiftsEnabled: boolean;
        bookingRulesEnabled: boolean;
        appointmentBookingEnabled: boolean;
        doubleBookingEnabled: boolean;
        appointmentBufferEnabled: boolean;
        appointmentBufferMinutes: number;
        confirmationTimeoutEnabled: boolean;
        confirmationTimeoutHours: import("../../../generated/prisma/enums").BookingHourOption;
        minimumBookingNoticeEnabled: boolean;
        minimumBookingNoticeHours: import("../../../generated/prisma/enums").BookingHourOption;
        rescheduleNoticeEnabled: boolean;
        rescheduleNoticeHours: import("../../../generated/prisma/enums").BookingHourOption;
    }>;
    upsert(clinicId: string, data: UpdateSchedulingSettingsInput): Promise<{
        id: string;
        clinicId: string;
        morningStartMinute: number;
        morningEndMinute: number;
        eveningStartMinute: number;
        eveningEndMinute: number;
        onlineBookingEnabled: boolean;
        schedulingEnabled: boolean;
        workDays: import("../staff-scheduling/staff-scheduling.type").Weekday[];
        shiftsEnabled: boolean;
        bookingRulesEnabled: boolean;
        appointmentBookingEnabled: boolean;
        doubleBookingEnabled: boolean;
        appointmentBufferEnabled: boolean;
        appointmentBufferMinutes: number;
        confirmationTimeoutEnabled: boolean;
        confirmationTimeoutHours: import("../../../generated/prisma/enums").BookingHourOption;
        minimumBookingNoticeEnabled: boolean;
        minimumBookingNoticeHours: import("../../../generated/prisma/enums").BookingHourOption;
        rescheduleNoticeEnabled: boolean;
        rescheduleNoticeHours: import("../../../generated/prisma/enums").BookingHourOption;
    }>;
};
