import { z } from "zod";
import type { Prisma } from "@/generated/prisma/client";
export declare const createSupplierSchema: z.ZodObject<{
    logo: z.ZodOptional<z.ZodString>;
    legalName: z.ZodString;
    type: z.ZodString;
    commercialReg: z.ZodString;
    supplierCode: z.ZodString;
    description: z.ZodOptional<z.ZodString>;
    categories: z.ZodArray<z.ZodString>;
    products: z.ZodDefault<z.ZodOptional<z.ZodArray<z.ZodString>>>;
    leadTimeDays: z.ZodCoercedNumber<unknown>;
    minOrderQty: z.ZodCoercedNumber<unknown>;
    supportsReturns: z.ZodDefault<z.ZodOptional<z.ZodBoolean>>;
    returnPolicy: z.ZodOptional<z.ZodString>;
    contactName: z.ZodString;
    contactTitle: z.ZodOptional<z.ZodString>;
    phone: z.ZodString;
    email: z.ZodUnion<[z.ZodOptional<z.ZodString>, z.ZodLiteral<"">]>;
    website: z.ZodOptional<z.ZodString>;
    country: z.ZodOptional<z.ZodString>;
    city: z.ZodOptional<z.ZodString>;
    address: z.ZodOptional<z.ZodString>;
    mapUrl: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export type CreateSupplierFormInput = z.infer<typeof createSupplierSchema>;
export type CreateSupplierInput = Pick<Prisma.SupplierUncheckedCreateInput, "clinicId" | "logo" | "legalName" | "type" | "commercialReg" | "supplierCode" | "description" | "categories" | "products" | "leadTimeDays" | "minOrderQty" | "supportsReturns" | "returnPolicy" | "contactName" | "contactTitle" | "phone" | "email" | "website" | "country" | "city" | "address" | "mapUrl">;
export declare const supplierSelect: {
    readonly id: true;
    readonly code: true;
    readonly legalName: true;
    readonly type: true;
    readonly logo: true;
    readonly commercialReg: true;
    readonly supplierCode: true;
    readonly description: true;
    readonly rating: true;
    readonly categories: true;
    readonly products: true;
    readonly leadTimeDays: true;
    readonly minOrderQty: true;
    readonly supportsReturns: true;
    readonly returnPolicy: true;
    readonly contactName: true;
    readonly contactTitle: true;
    readonly phone: true;
    readonly email: true;
    readonly website: true;
    readonly country: true;
    readonly city: true;
    readonly address: true;
    readonly mapUrl: true;
    readonly active: true;
    readonly createdAt: true;
};
export type SupplierResponse = Prisma.SupplierGetPayload<{
    select: typeof supplierSelect;
}>;
export type ItemSupplierResponse = Pick<SupplierResponse, "id" | "legalName" | "rating"> & {
    isPrimary: boolean;
    lastOrderAt: Date | null;
    price: number | null;
};
