import { AccountRootType, AccountType, BalanceMustBe } from "@/generated/prisma/enums";
/**
 * Shared DB fixture for the GL engine suites: one clinic with a 2026 fiscal year, company
 * accounting settings (base SAR + round-off accounts) and a minimal postable chart.
 */
export declare function createGlFixture(): Promise<{
    clinicId: string;
    accounts: {
        assets: {
            id: string;
            clinicId: string;
            disabled: boolean;
            createdAt: Date;
            updatedAt: Date;
            accountName: string;
            accountNumber: string | null;
            parentAccountId: string | null;
            isGroup: boolean;
            rootType: AccountRootType;
            reportType: import("@/generated/prisma/enums").AccountReportType;
            accountType: AccountType | null;
            accountCurrencyCode: string;
            taxRate: import("@prisma/client-runtime-utils").Decimal | null;
            balanceMustBe: BalanceMustBe;
            freezeAccount: boolean;
            lft: number;
            rgt: number;
        };
        cash: {
            id: string;
            clinicId: string;
            disabled: boolean;
            createdAt: Date;
            updatedAt: Date;
            accountName: string;
            accountNumber: string | null;
            parentAccountId: string | null;
            isGroup: boolean;
            rootType: AccountRootType;
            reportType: import("@/generated/prisma/enums").AccountReportType;
            accountType: AccountType | null;
            accountCurrencyCode: string;
            taxRate: import("@prisma/client-runtime-utils").Decimal | null;
            balanceMustBe: BalanceMustBe;
            freezeAccount: boolean;
            lft: number;
            rgt: number;
        };
        bank: {
            id: string;
            clinicId: string;
            disabled: boolean;
            createdAt: Date;
            updatedAt: Date;
            accountName: string;
            accountNumber: string | null;
            parentAccountId: string | null;
            isGroup: boolean;
            rootType: AccountRootType;
            reportType: import("@/generated/prisma/enums").AccountReportType;
            accountType: AccountType | null;
            accountCurrencyCode: string;
            taxRate: import("@prisma/client-runtime-utils").Decimal | null;
            balanceMustBe: BalanceMustBe;
            freezeAccount: boolean;
            lft: number;
            rgt: number;
        };
        income: {
            id: string;
            clinicId: string;
            disabled: boolean;
            createdAt: Date;
            updatedAt: Date;
            accountName: string;
            accountNumber: string | null;
            parentAccountId: string | null;
            isGroup: boolean;
            rootType: AccountRootType;
            reportType: import("@/generated/prisma/enums").AccountReportType;
            accountType: AccountType | null;
            accountCurrencyCode: string;
            taxRate: import("@prisma/client-runtime-utils").Decimal | null;
            balanceMustBe: BalanceMustBe;
            freezeAccount: boolean;
            lft: number;
            rgt: number;
        };
        expenses: {
            id: string;
            clinicId: string;
            disabled: boolean;
            createdAt: Date;
            updatedAt: Date;
            accountName: string;
            accountNumber: string | null;
            parentAccountId: string | null;
            isGroup: boolean;
            rootType: AccountRootType;
            reportType: import("@/generated/prisma/enums").AccountReportType;
            accountType: AccountType | null;
            accountCurrencyCode: string;
            taxRate: import("@prisma/client-runtime-utils").Decimal | null;
            balanceMustBe: BalanceMustBe;
            freezeAccount: boolean;
            lft: number;
            rgt: number;
        };
        roundOff: {
            id: string;
            clinicId: string;
            disabled: boolean;
            createdAt: Date;
            updatedAt: Date;
            accountName: string;
            accountNumber: string | null;
            parentAccountId: string | null;
            isGroup: boolean;
            rootType: AccountRootType;
            reportType: import("@/generated/prisma/enums").AccountReportType;
            accountType: AccountType | null;
            accountCurrencyCode: string;
            taxRate: import("@prisma/client-runtime-utils").Decimal | null;
            balanceMustBe: BalanceMustBe;
            freezeAccount: boolean;
            lft: number;
            rgt: number;
        };
        roundOffOpening: {
            id: string;
            clinicId: string;
            disabled: boolean;
            createdAt: Date;
            updatedAt: Date;
            accountName: string;
            accountNumber: string | null;
            parentAccountId: string | null;
            isGroup: boolean;
            rootType: AccountRootType;
            reportType: import("@/generated/prisma/enums").AccountReportType;
            accountType: AccountType | null;
            accountCurrencyCode: string;
            taxRate: import("@prisma/client-runtime-utils").Decimal | null;
            balanceMustBe: BalanceMustBe;
            freezeAccount: boolean;
            lft: number;
            rgt: number;
        };
        disabledAccount: {
            id: string;
            clinicId: string;
            disabled: boolean;
            createdAt: Date;
            updatedAt: Date;
            accountName: string;
            accountNumber: string | null;
            parentAccountId: string | null;
            isGroup: boolean;
            rootType: AccountRootType;
            reportType: import("@/generated/prisma/enums").AccountReportType;
            accountType: AccountType | null;
            accountCurrencyCode: string;
            taxRate: import("@prisma/client-runtime-utils").Decimal | null;
            balanceMustBe: BalanceMustBe;
            freezeAccount: boolean;
            lft: number;
            rgt: number;
        };
        frozenAccount: {
            id: string;
            clinicId: string;
            disabled: boolean;
            createdAt: Date;
            updatedAt: Date;
            accountName: string;
            accountNumber: string | null;
            parentAccountId: string | null;
            isGroup: boolean;
            rootType: AccountRootType;
            reportType: import("@/generated/prisma/enums").AccountReportType;
            accountType: AccountType | null;
            accountCurrencyCode: string;
            taxRate: import("@prisma/client-runtime-utils").Decimal | null;
            balanceMustBe: BalanceMustBe;
            freezeAccount: boolean;
            lft: number;
            rgt: number;
        };
        debitOnly: {
            id: string;
            clinicId: string;
            disabled: boolean;
            createdAt: Date;
            updatedAt: Date;
            accountName: string;
            accountNumber: string | null;
            parentAccountId: string | null;
            isGroup: boolean;
            rootType: AccountRootType;
            reportType: import("@/generated/prisma/enums").AccountReportType;
            accountType: AccountType | null;
            accountCurrencyCode: string;
            taxRate: import("@prisma/client-runtime-utils").Decimal | null;
            balanceMustBe: BalanceMustBe;
            freezeAccount: boolean;
            lft: number;
            rgt: number;
        };
        receivable: {
            id: string;
            clinicId: string;
            disabled: boolean;
            createdAt: Date;
            updatedAt: Date;
            accountName: string;
            accountNumber: string | null;
            parentAccountId: string | null;
            isGroup: boolean;
            rootType: AccountRootType;
            reportType: import("@/generated/prisma/enums").AccountReportType;
            accountType: AccountType | null;
            accountCurrencyCode: string;
            taxRate: import("@prisma/client-runtime-utils").Decimal | null;
            balanceMustBe: BalanceMustBe;
            freezeAccount: boolean;
            lft: number;
            rgt: number;
        };
        payable: {
            id: string;
            clinicId: string;
            disabled: boolean;
            createdAt: Date;
            updatedAt: Date;
            accountName: string;
            accountNumber: string | null;
            parentAccountId: string | null;
            isGroup: boolean;
            rootType: AccountRootType;
            reportType: import("@/generated/prisma/enums").AccountReportType;
            accountType: AccountType | null;
            accountCurrencyCode: string;
            taxRate: import("@prisma/client-runtime-utils").Decimal | null;
            balanceMustBe: BalanceMustBe;
            freezeAccount: boolean;
            lft: number;
            rgt: number;
        };
        vat: {
            id: string;
            clinicId: string;
            disabled: boolean;
            createdAt: Date;
            updatedAt: Date;
            accountName: string;
            accountNumber: string | null;
            parentAccountId: string | null;
            isGroup: boolean;
            rootType: AccountRootType;
            reportType: import("@/generated/prisma/enums").AccountReportType;
            accountType: AccountType | null;
            accountCurrencyCode: string;
            taxRate: import("@prisma/client-runtime-utils").Decimal | null;
            balanceMustBe: BalanceMustBe;
            freezeAccount: boolean;
            lft: number;
            rgt: number;
        };
    };
    costCenter: {
        id: string;
        clinicId: string;
        disabled: boolean;
        createdById: string | null;
        createdAt: Date;
        updatedAt: Date;
        isGroup: boolean;
        lft: number;
        rgt: number;
        costCenterName: string;
        costCenterNumber: string | null;
        parentCostCenterId: string | null;
    };
    parties: {
        owner: {
            name: string;
            address: string | null;
            id: string;
            clinicId: string;
            createdAt: Date;
            updatedAt: Date;
            email: string | null;
            phone: string;
            city: string | null;
            code: string;
            gender: import("@/generated/prisma/enums").Gender | null;
            country: string | null;
            notes: string | null;
            active: boolean;
            isDeleted: boolean;
            deletedAt: Date | null;
            editsCount: number;
            phoneE164: string | null;
            ownerType: import("@/generated/prisma/enums").OwnerType;
            relationship: import("@/generated/prisma/enums").OwnerRelationship | null;
        };
        supplier: {
            type: string;
            address: string | null;
            id: string;
            clinicId: string;
            createdAt: Date;
            updatedAt: Date;
            logo: string | null;
            email: string | null;
            phone: string;
            website: string | null;
            city: string | null;
            description: string | null;
            code: string;
            categories: string[];
            country: string | null;
            active: boolean;
            isDeleted: boolean;
            deletedAt: Date | null;
            legalName: string;
            commercialReg: string | null;
            supplierCode: string | null;
            rating: number | null;
            products: string[];
            leadTimeDays: number | null;
            minOrderQty: number | null;
            supportsReturns: boolean;
            returnPolicy: string | null;
            contactName: string;
            contactTitle: string | null;
            mapUrl: string | null;
        };
    };
    cleanup(): Promise<void>;
}>;
